from decimal import Decimal

from django.core.management.base import BaseCommand

from menu.models import Category, Product, ProductOption


class Command(BaseCommand):
    help = 'Create demo data for the QuickMenu MVP.'

    def handle(self, *args, **options):
        categories = [
            ('combos', 'Combos', 1),
            ('promocoes', 'Promocoes', 2),
            ('lanches', 'Lanches', 3),
            ('personalizar', 'Personalizar pedido', 4),
        ]
        category_map = {}
        for slug, name, order in categories:
            category, _ = Category.objects.update_or_create(
                slug=slug,
                defaults={'name': name, 'order': order, 'active': True},
            )
            category_map[slug] = category

        products = [
            {
                'slug': 'combo-smash',
                'category': category_map['combos'],
                'name': 'Combo Smash',
                'description': 'Smash Classico, batata media e refrigerante medio.',
                'ingredients': 'Hamburguer, acompanhamento e bebida.',
                'price': Decimal('36.90'),
                'kind': 'combo',
                'image': '#ffd8c8',
                'order': 1,
            },
            {
                'slug': 'combo-bacon',
                'category': category_map['combos'],
                'name': 'Combo Bacon',
                'description': 'Smash Bacon, batata media e refrigerante.',
                'ingredients': 'Bacon crocante, cheddar, batata e bebida.',
                'price': Decimal('41.90'),
                'kind': 'combo',
                'image': '#f2c58a',
                'order': 2,
            },
            {
                'slug': 'combo-cheddar-duplo',
                'category': category_map['combos'],
                'name': 'Combo Cheddar Duplo',
                'description': 'Duplo Cheddar, batata media e refrigerante medio.',
                'ingredients': 'Duas carnes, cheddar cremoso, batata crocante e bebida.',
                'price': Decimal('45.90'),
                'kind': 'combo',
                'image': '#f0b84f',
                'order': 3,
            },
            {
                'slug': 'combo-chicken-crispy',
                'category': category_map['combos'],
                'name': 'Combo Chicken Crispy',
                'description': 'Chicken Crispy com batata media e refrigerante.',
                'ingredients': 'Frango crocante, salada, molho especial, batata e bebida.',
                'price': Decimal('39.90'),
                'kind': 'combo',
                'image': '#dbe7a2',
                'order': 4,
            },
            {
                'slug': 'combo-bbq',
                'category': category_map['combos'],
                'name': 'Combo BBQ',
                'description': 'Burger BBQ, batata rustica e refrigerante.',
                'ingredients': 'Carne smash, queijo, cebola crispy, molho barbecue e batata rustica.',
                'price': Decimal('43.90'),
                'kind': 'combo',
                'image': '#c98a5f',
                'order': 5,
            },
            {
                'slug': 'combo-picanha',
                'category': category_map['combos'],
                'name': 'Combo Picanha',
                'description': 'Burger Picanha, batata grande e refrigerante.',
                'ingredients': 'Burger de picanha, queijo prato, maionese da casa, batata e bebida.',
                'price': Decimal('49.90'),
                'kind': 'combo',
                'image': '#d1996f',
                'order': 6,
            },
            {
                'slug': 'combo-vegetariano',
                'category': category_map['combos'],
                'name': 'Combo Vegetariano',
                'description': 'Burger vegetariano, onion rings e suco.',
                'ingredients': 'Hamburguer vegetal, queijo, salada fresca, onion rings e bebida.',
                'price': Decimal('42.90'),
                'kind': 'combo',
                'image': '#b7d99a',
                'order': 7,
            },
            {
                'slug': 'combo-kids',
                'category': category_map['combos'],
                'name': 'Combo Kids',
                'description': 'Mini burger, batata pequena e suco.',
                'ingredients': 'Mini hamburguer com queijo, batata pequena e bebida leve.',
                'price': Decimal('29.90'),
                'kind': 'combo',
                'image': '#ffd6e0',
                'order': 8,
            },
            {
                'slug': 'combo-hot-dog',
                'category': category_map['combos'],
                'name': 'Combo Hot Dog',
                'description': 'Hot dog especial, batata pequena e refrigerante.',
                'ingredients': 'Salsicha, molho, batata palha, queijo, batata e bebida.',
                'price': Decimal('32.90'),
                'kind': 'combo',
                'image': '#f6c45f',
                'order': 9,
            },
            {
                'slug': 'combo-salada-crispy',
                'category': category_map['combos'],
                'name': 'Combo Salada Crispy',
                'description': 'Burger leve com frango crispy, salada e agua.',
                'ingredients': 'Frango crocante, folhas, tomate, molho iogurte e bebida.',
                'price': Decimal('37.90'),
                'kind': 'combo',
                'image': '#c8e7bf',
                'order': 10,
            },
            {
                'slug': 'combo-triplo-smash',
                'category': category_map['combos'],
                'name': 'Combo Triplo Smash',
                'description': 'Triplo smash, batata grande e refrigerante grande.',
                'ingredients': 'Tres carnes smash, muito queijo, batata grande e bebida.',
                'price': Decimal('55.90'),
                'kind': 'combo',
                'image': '#e3a15f',
                'order': 11,
            },
            {
                'slug': 'dupla-smash',
                'category': category_map['promocoes'],
                'name': 'Dupla Smash',
                'description': '2 Smash Burgers e 1 batata grande.',
                'ingredients': 'Oferta ideal para compartilhar.',
                'price': Decimal('59.90'),
                'promotional_price': Decimal('44.90'),
                'kind': 'promotion',
                'image': '#ffc6b7',
                'order': 1,
            },
            {
                'slug': 'terca-do-bacon',
                'category': category_map['promocoes'],
                'name': 'Terca do Bacon',
                'description': 'Smash Bacon com desconto especial.',
                'ingredients': 'Lanche com bacon, cheddar e molho da casa em promocao.',
                'price': Decimal('27.90'),
                'promotional_price': Decimal('22.90'),
                'kind': 'promotion',
                'image': '#efb077',
                'order': 2,
            },
            {
                'slug': 'combo-casal',
                'category': category_map['promocoes'],
                'name': 'Combo Casal',
                'description': '2 burgers, 2 bebidas e 1 batata grande.',
                'ingredients': 'Dois lanches classicos, duas bebidas e uma porcao para dividir.',
                'price': Decimal('78.90'),
                'promotional_price': Decimal('64.90'),
                'kind': 'promotion',
                'image': '#f4b8a8',
                'order': 3,
            },
            {
                'slug': 'hora-do-smash',
                'category': category_map['promocoes'],
                'name': 'Hora do Smash',
                'description': 'Smash Classico por preco promocional.',
                'ingredients': 'Pao brioche, carne smash, queijo e molho da casa.',
                'price': Decimal('22.90'),
                'promotional_price': Decimal('18.90'),
                'kind': 'promotion',
                'image': '#f8d58d',
                'order': 4,
            },
            {
                'slug': 'batata-em-dobro',
                'category': category_map['promocoes'],
                'name': 'Batata em Dobro',
                'description': 'Burger Classico com duas batatas medias.',
                'ingredients': 'Lanche classico acompanhado de duas porcoes de batata.',
                'price': Decimal('42.90'),
                'promotional_price': Decimal('34.90'),
                'kind': 'promotion',
                'image': '#f5d47c',
                'order': 5,
            },
            {
                'slug': 'festival-cheddar',
                'category': category_map['promocoes'],
                'name': 'Festival Cheddar',
                'description': 'Burger com cheddar extra e batata media.',
                'ingredients': 'Carne smash, cheddar em dobro, cebola crispy e batata.',
                'price': Decimal('44.90'),
                'promotional_price': Decimal('36.90'),
                'kind': 'promotion',
                'image': '#f1b943',
                'order': 6,
            },
            {
                'slug': 'oferta-crispy',
                'category': category_map['promocoes'],
                'name': 'Oferta Crispy',
                'description': 'Chicken Crispy com bebida por preco reduzido.',
                'ingredients': 'Frango empanado crocante, salada, molho e refrigerante.',
                'price': Decimal('32.90'),
                'promotional_price': Decimal('27.90'),
                'kind': 'promotion',
                'image': '#d9e9b8',
                'order': 7,
            },
            {
                'slug': 'smash-classico',
                'category': category_map['lanches'],
                'name': 'Smash Classico',
                'description': 'Pao brioche, carne 120g, queijo e molho da casa.',
                'ingredients': 'Pao brioche, carne 120g, queijo e molho da casa.',
                'price': Decimal('22.90'),
                'kind': 'burger',
                'image': '#f6e0a6',
                'order': 1,
            },
            {
                'slug': 'smash-bacon',
                'category': category_map['lanches'],
                'name': 'Smash Bacon',
                'description': 'Pao brioche, smash, cheddar e bacon.',
                'ingredients': 'Pao brioche, carne smash, cheddar cremoso, bacon e molho.',
                'price': Decimal('27.90'),
                'kind': 'burger',
                'image': '#e8b47a',
                'order': 2,
            },
            {
                'slug': 'duplo-cheddar',
                'category': category_map['lanches'],
                'name': 'Duplo Cheddar',
                'description': 'Duas carnes, cheddar e cebola caramelizada.',
                'ingredients': 'Pao, duas carnes, cheddar, cebola caramelizada e molho.',
                'price': Decimal('31.90'),
                'kind': 'burger',
                'image': '#f3be57',
                'order': 3,
            },
            {
                'slug': 'chicken-crispy',
                'category': category_map['lanches'],
                'name': 'Chicken Crispy',
                'description': 'Frango crocante, alface e molho especial.',
                'ingredients': 'Pao, frango empanado, alface, queijo e molho especial.',
                'price': Decimal('25.90'),
                'kind': 'burger',
                'image': '#d9e9b8',
                'order': 4,
            },
            {
                'slug': 'bbq-bacon',
                'category': category_map['lanches'],
                'name': 'BBQ Bacon',
                'description': 'Carne smash, bacon, queijo prato e barbecue.',
                'ingredients': 'Pao brioche, carne 120g, bacon crocante, queijo prato e molho barbecue.',
                'price': Decimal('29.90'),
                'kind': 'burger',
                'image': '#c98a5f',
                'order': 5,
            },
            {
                'slug': 'onion-cheddar',
                'category': category_map['lanches'],
                'name': 'Onion Cheddar',
                'description': 'Smash com cheddar e cebola crispy.',
                'ingredients': 'Pao, carne smash, cheddar cremoso, cebola crispy e molho da casa.',
                'price': Decimal('28.90'),
                'kind': 'burger',
                'image': '#efc45b',
                'order': 6,
            },
            {
                'slug': 'pepper-jack',
                'category': category_map['lanches'],
                'name': 'Pepper Jack',
                'description': 'Burger picante com queijo, jalapeno e molho apimentado.',
                'ingredients': 'Pao, carne smash, queijo, jalapeno, pimenta suave e maionese spicy.',
                'price': Decimal('30.90'),
                'kind': 'burger',
                'image': '#de624c',
                'order': 7,
            },
            {
                'slug': 'mushroom-swiss',
                'category': category_map['lanches'],
                'name': 'Mushroom Swiss',
                'description': 'Burger com cogumelos salteados e queijo suico.',
                'ingredients': 'Pao brioche, carne, cogumelos, queijo suico e molho cremoso.',
                'price': Decimal('33.90'),
                'kind': 'burger',
                'image': '#c9b39b',
                'order': 8,
            },
            {
                'slug': 'picanha-classic',
                'category': category_map['lanches'],
                'name': 'Picanha Classic',
                'description': 'Burger de picanha, queijo prato e maionese da casa.',
                'ingredients': 'Pao brioche, burger de picanha, queijo prato, alface, tomate e maionese.',
                'price': Decimal('36.90'),
                'kind': 'burger',
                'image': '#d1996f',
                'order': 9,
            },
            {
                'slug': 'triplo-smash',
                'category': category_map['lanches'],
                'name': 'Triplo Smash',
                'description': 'Tres carnes smash com queijo derretido.',
                'ingredients': 'Pao, tres carnes smash, queijo em camadas, pickles e molho especial.',
                'price': Decimal('39.90'),
                'kind': 'burger',
                'image': '#e3a15f',
                'order': 10,
            },
            {
                'slug': 'egg-burger',
                'category': category_map['lanches'],
                'name': 'Egg Burger',
                'description': 'Smash com ovo, queijo e bacon.',
                'ingredients': 'Pao, carne smash, ovo, queijo, bacon e maionese da casa.',
                'price': Decimal('31.90'),
                'kind': 'burger',
                'image': '#f2d179',
                'order': 11,
            },
            {
                'slug': 'salad-burger',
                'category': category_map['lanches'],
                'name': 'Salad Burger',
                'description': 'Burger com bastante salada fresca.',
                'ingredients': 'Pao tradicional, carne, queijo, alface, tomate, cebola roxa e molho leve.',
                'price': Decimal('26.90'),
                'kind': 'burger',
                'image': '#b8d991',
                'order': 12,
            },
            {
                'slug': 'veggie-green',
                'category': category_map['lanches'],
                'name': 'Veggie Green',
                'description': 'Hamburguer vegetal com queijo, salada e molho verde.',
                'ingredients': 'Pao integral, burger vegetal, queijo, folhas, tomate e molho de ervas.',
                'price': Decimal('29.90'),
                'kind': 'burger',
                'image': '#a7d7a0',
                'order': 13,
            },
            {
                'slug': 'costela-smash',
                'category': category_map['lanches'],
                'name': 'Costela Smash',
                'description': 'Burger de costela com queijo e cebola caramelizada.',
                'ingredients': 'Pao brioche, burger de costela, queijo, cebola caramelizada e molho escuro.',
                'price': Decimal('35.90'),
                'kind': 'burger',
                'image': '#b98261',
                'order': 14,
            },
            {
                'slug': 'gorgonzola-crispy',
                'category': category_map['lanches'],
                'name': 'Gorgonzola Crispy',
                'description': 'Smash com creme de gorgonzola e cebola crispy.',
                'ingredients': 'Pao, carne smash, creme de gorgonzola, cebola crispy e rucula.',
                'price': Decimal('34.90'),
                'kind': 'burger',
                'image': '#d7d0b0',
                'order': 15,
            },
            {
                'slug': 'frango-ranch',
                'category': category_map['lanches'],
                'name': 'Frango Ranch',
                'description': 'Frango grelhado com queijo, salada e molho ranch.',
                'ingredients': 'Pao, file de frango grelhado, queijo, alface, tomate e molho ranch.',
                'price': Decimal('27.90'),
                'kind': 'burger',
                'image': '#dcd9a7',
                'order': 16,
            },
            {
                'slug': 'crispy-spicy',
                'category': category_map['lanches'],
                'name': 'Crispy Spicy',
                'description': 'Frango crocante com molho levemente apimentado.',
                'ingredients': 'Pao, frango empanado, queijo, alface, pickles e molho spicy.',
                'price': Decimal('28.90'),
                'kind': 'burger',
                'image': '#e07a50',
                'order': 17,
            },
            {
                'slug': 'mini-smash',
                'category': category_map['lanches'],
                'name': 'Mini Smash',
                'description': 'Versao menor do smash classico com queijo.',
                'ingredients': 'Mini pao, carne smash, queijo e molho da casa.',
                'price': Decimal('17.90'),
                'kind': 'burger',
                'image': '#f3cf9b',
                'order': 18,
            },
            {
                'slug': 'monster-bacon',
                'category': category_map['lanches'],
                'name': 'Monster Bacon',
                'description': 'Burger alto com duas carnes, cheddar e muito bacon.',
                'ingredients': 'Pao brioche, duas carnes, cheddar, bacon em tiras, cebola e molho especial.',
                'price': Decimal('42.90'),
                'kind': 'burger',
                'image': '#bd7659',
                'order': 19,
            },
            {
                'slug': 'monte-seu-hamburguer',
                'category': category_map['personalizar'],
                'name': 'Monte seu hamburguer',
                'description': 'Escolha pao, carnes, queijo e adicionais.',
                'ingredients': 'Preco calculado conforme suas escolhas.',
                'price': Decimal('14.90'),
                'kind': 'custom',
                'image': '#d6eee4',
                'order': 1,
            },
        ]

        product_images = {
            'combo-smash': 'images/products/combo-smash.png',
            'combo-bacon': 'images/products/combo-bacon.png',
            'combo-cheddar-duplo': 'images/products/combo-cheddar-duplo.png',
            'combo-chicken-crispy': 'images/products/combo-chicken-crispy.png',
            'combo-bbq': 'images/products/combo-bbq.png',
            'combo-picanha': 'images/products/combo-picanha.png',
            'combo-vegetariano': 'images/products/combo-vegetariano.png',
            'combo-kids': 'images/products/combo-kids.png',
            'combo-hot-dog': 'images/products/combo-hot-dog.png',
            'combo-salada-crispy': 'images/products/combo-salada-crispy.png',
            'combo-triplo-smash': 'images/products/combo-triplo-smash.png',
            'dupla-smash': 'images/products/dupla-smash.png',
            'terca-do-bacon': 'images/products/terca-do-bacon.png',
            'combo-casal': 'images/products/combo-casal.png',
            'hora-do-smash': 'images/products/hora-do-smash.png',
            'batata-em-dobro': 'images/products/batata-em-dobro.png',
            'festival-cheddar': 'images/products/festival-cheddar.png',
            'oferta-crispy': 'images/products/oferta-crispy.png',
            'smash-classico': 'images/products/smash-classico.png',
            'smash-bacon': 'images/products/smash-bacon.png',
            'duplo-cheddar': 'images/products/duplo-cheddar.png',
            'chicken-crispy': 'images/products/chicken-crispy.png',
            'bbq-bacon': 'images/products/bbq-bacon.png',
            'onion-cheddar': 'images/products/onion-cheddar.png',
            'pepper-jack': 'images/products/pepper-jack.png',
            'mushroom-swiss': 'images/products/mushroom-swiss.png',
            'picanha-classic': 'images/products/picanha-classic.png',
            'triplo-smash': 'images/products/triplo-smash.png',
            'egg-burger': 'images/products/egg-burger.png',
            'salad-burger': 'images/products/salad-burger.png',
            'veggie-green': 'images/products/veggie-green.png',
            'costela-smash': 'images/products/costela-smash.png',
            'gorgonzola-crispy': 'images/products/gorgonzola-crispy.png',
            'frango-ranch': 'images/products/frango-ranch.png',
            'crispy-spicy': 'images/products/crispy-spicy.png',
            'mini-smash': 'images/products/mini-smash.png',
            'monster-bacon': 'images/products/monster-bacon.png',
            'monte-seu-hamburguer': 'images/products/monte-seu-hamburguer.png',
        }

        for data in products:
            data['image'] = product_images.get(data['slug'], data.get('image', ''))
            Product.objects.update_or_create(
                slug=data['slug'],
                defaults={**data, 'active': True},
            )

        options = [
            ('Coca-Cola', 'drink', Decimal('7.00'), 1),
            ('Guarana', 'drink', Decimal('7.00'), 2),
            ('Fanta', 'drink', Decimal('7.00'), 3),
            ('Sprite', 'drink', Decimal('7.00'), 4),
            ('Agua', 'drink', Decimal('4.00'), 5),
            ('Batata pequena', 'side', Decimal('8.00'), 1),
            ('Batata media', 'side', Decimal('11.00'), 2),
            ('Batata grande', 'side', Decimal('14.00'), 3),
            ('Onion Rings', 'side', Decimal('13.00'), 4),
            ('Brioche', 'bread', Decimal('0.00'), 1),
            ('Australiano', 'bread', Decimal('2.00'), 2),
            ('Tradicional', 'bread', Decimal('0.00'), 3),
            ('1 carne', 'meat', Decimal('0.00'), 1),
            ('2 carnes', 'meat', Decimal('7.00'), 2),
            ('3 carnes', 'meat', Decimal('14.00'), 3),
            ('Cheddar', 'cheese', Decimal('3.00'), 1),
            ('Mussarela', 'cheese', Decimal('3.00'), 2),
            ('Sem queijo', 'cheese', Decimal('0.00'), 3),
            ('Bacon', 'extra', Decimal('5.00'), 1),
            ('Cebola caramelizada', 'extra', Decimal('3.00'), 2),
            ('Ovo', 'extra', Decimal('4.00'), 3),
            ('Molho especial', 'extra', Decimal('2.00'), 4),
        ]

        for name, option_type, price, order in options:
            ProductOption.objects.update_or_create(
                name=name,
                option_type=option_type,
                product=None,
                defaults={'price': price, 'active': True, 'order': order},
            )

        self.stdout.write(self.style.SUCCESS('Demo data ready.'))
